# Generated by Django 4.2.6 on 2023-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='Активировать'),
        ),
    ]
