# Generated by Django 4.2.6 on 2023-11-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_publication', 'Can publication')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
